settings:
  allow-end: true
  warn-on-overload: true
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: 4000
  query-plugins: true
  deprecated-verbose: default
  shutdown-message: Server closed
  minimum-api: none
  use-map-color-cache: true
spawn-limits:
  monsters: 40
  animals: 8
  water-animals: 3
  water-ambient: 10
  water-underground-creature: 3
  axolotls: 3
  ambient: 10
chunk-gc:
  period-in-ticks: 600
ticks-per:
  animal-spawns: 600
  monster-spawns: 2
  water-spawns: 2
  water-ambient-spawns: 2
  water-underground-creature-spawns: 2
  axolotl-spawns: 2
  ambient-spawns: 2
  autosave: 12000
aliases: now-in-commands.yml
